# name: Android CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Get Your Code
#         uses: actions/checkout@v2

#       - name: Validate gradle
#         uses: gradle/actions/wrapper-validation@v3

#       - name: set up JDK 21
#         uses: actions/setup-java@v4
#         with:
#           java-version: "21"
#           distribution: "zulu"

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20"

#       - name: Run Yarn Install
#         run: cd react_native && yarn

#       - name: Build App
#         run: cd react_native/android && ./gradlew assembleRelease

#       - name: Upload APK to Artifacts
#         uses: actions/upload-artifact@v4
#         with: 
#             name: android_apk
#             path: react_native/android/app/build/outputs/apk/release/app-release.apk
#             retention-days: 3