name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Your Code
        uses: actions/checkout@v2

      - name: Validate gradle
        uses: gradle/actions/wrapper-validation@v3

      - name: Say Hello to the World
        run: echo "Hello, World!"
